name: CD

on:
  push:
    branches: [main, master]
  workflow_dispatch:

jobs:
  deploy_canary:
    name: Deploy to canary
    runs-on: ubuntu-latest
    environment: canary
    steps:
      - uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm i -g vercel

      - name: Deploy to Vercel
        run: vercel --prod --token ${{ secrets.VERCEL_TOKEN }} --yes

  deploy_staging:
    name: Deploy to staging
    runs-on: ubuntu-latest
    environment: staging
    needs: deploy_canary
    steps:
      - uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm i -g vercel

      - name: Deploy to Vercel
        run: vercel --prod --token ${{ secrets.VERCEL_TOKEN }} --yes

  deploy_demo:
    name: Deploy to demo
    runs-on: ubuntu-latest
    environment: demo
    needs: deploy_staging
    steps:
      - uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm i -g vercel

      - name: Deploy to Vercel
        run: vercel --prod --token ${{ secrets.VERCEL_TOKEN }} --yes

  deploy_trial:
    name: Deploy to trial
    runs-on: ubuntu-latest
    environment: trial
    needs: deploy_demo
    steps:
      - uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm i -g vercel

      - name: Deploy to Vercel
        run: vercel --prod --token ${{ secrets.VERCEL_TOKEN }} --yes

  deploy_production:
    name: Deploy to production
    runs-on: ubuntu-latest
    environment: production
    needs: deploy_trial
    steps:
      - uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm i -g vercel

      - name: Deploy to Vercel
        run: vercel --prod --token ${{ secrets.VERCEL_TOKEN }} --yes

